/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identidad/contexto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Contexto
         * @description Devuelve usuario/rol/tenant/sesión ya resueltos a partir del JWT de la request.
         *
         *     Endpoint de verificación end-to-end de la capa de auth (útil para QA y para el
         *     frontend, todavía sin construir) -- equivalente a un `GET /me`.
         */
        get: operations["obtener_contexto_identidad_contexto_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar
         * @description Registra una cuenta nueva en Supabase Auth. NO asigna ningún rol -- `cliente` se
         *     autoasigna recién en la primera reserva (ver `docs/ARCHITECTURE.md`).
         *
         *     El backend hace de proxy de Supabase Auth (en vez de que el frontend llame a
         *     `supabase-js` directo) para poder probarlo desde `/docs` y para que la dependencia de
         *     Supabase Auth quede encerrada en `infraestructura/`.
         *
         *     Anti-enumeración de cuentas: si no hay sesión inmediata, SIEMPRE responde `202` con
         *     el mismo mensaje genérico, sea el correo nuevo (confirmación pendiente) o ya
         *     registrado -- nunca un `409` ni ningún otro código que revele cuál de los dos casos
         *     ocurrió (ver `dominio.excepciones.RegistroSinSesionInmediata`).
         */
        post: operations["registrar_identidad_registro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/iniciar-sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar Sesion
         * @description Autentica un usuario ya registrado contra Supabase Auth y devuelve sus tokens.
         */
        post: operations["iniciar_sesion_identidad_iniciar_sesion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Perfil
         * @description Perfil de gestión de cuenta del usuario autenticado (`perfiles_usuario`,
         *     `011_perfil_cuenta_gestion.sql`).
         *
         *     Usa `DatosTokenDep` (solo JWT validado), NO `ContextoIdentidadDep`: gestión de cuenta
         *     es tenant-agnóstica y debe funcionar incluso para un usuario sin ningún rol asignado
         *     todavía -- ver el docstring de `PerfilCuentaRespuesta` para el porqué completo.
         */
        get: operations["obtener_perfil_identidad_perfil_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar Perfil
         * @description El propio usuario edita `nombre_completo`/`avatar_url`/`terminos_aceptados_at`+
         *     `terminos_version`/`onboarding_completado_at`. QUÉ columnas puede tocar lo decide
         *     únicamente Postgres (RLS + `restringir_columnas_perfil_usuario`) -- este endpoint usa
         *     el JWT del propio usuario, nunca la `secret` key, para que esa sea la única fuente de
         *     verdad. Ver `obtener_perfil` para por qué usa `DatosTokenDep` y no `ContextoIdentidadDep`.
         */
        patch: operations["actualizar_perfil_identidad_perfil_patch"];
        trace?: never;
    };
    "/identidad/recuperar-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recuperar Contrasena
         * @description Envía el correo de recuperación de contraseña vía Supabase Auth (`/recover`).
         *
         *     Anti-enumeración: SIEMPRE responde el mismo mensaje genérico y el mismo código,
         *     exista o no una cuenta con ese correo -- ver
         *     `dominio.puertos.AutenticadorPuerto.enviar_recuperacion_contrasena`. El punto más
         *     sensible de este PR: nunca introducir una rama que distinga ambos casos acá.
         */
        post: operations["recuperar_contrasena_identidad_recuperar_contrasena_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/restablecer-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restablecer Contrasena
         * @description Fija una nueva contraseña sobre la sesión de recuperación (`token_acceso`/
         *     `token_actualizacion`) que el frontend obtuvo al abrir el enlace del correo -- llama
         *     `updateUser` de GoTrue.
         */
        post: operations["restablecer_contrasena_identidad_restablecer_contrasena_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/cerrar-todas-las-sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar Todas Las Sesiones
         * @description Revoca TODAS las sesiones (todos los dispositivos) del usuario autenticado vía Auth
         *     Admin API de Supabase (`admin.sign_out` con `scope="global"`) -- ver
         *     `dominio.puertos.GestorCuentaPuerto.cerrar_todas_las_sesiones` para por qué esto (y no
         *     solo marcar `sesiones.cerrada_at`) es el mecanismo que realmente invalida las sesiones.
         *     Usa `DatosTokenDep`, no `ContextoIdentidadDep` -- ver `obtener_perfil`: cerrar todas
         *     tus sesiones no depende de tener un rol asignado.
         */
        post: operations["cerrar_todas_las_sesiones_identidad_cerrar_todas_las_sesiones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/eliminar-cuenta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Eliminar Cuenta
         * @description El usuario autenticado elimina (soft-delete) SU PROPIA cuenta.
         *
         *     `usuario_id` viene únicamente de `datos_token` (ya resuelto desde el JWT, ver
         *     `obtener_perfil` para por qué `DatosTokenDep` y no `ContextoIdentidadDep`) -- nunca de
         *     un body, para que nadie pueda pedir la eliminación de una cuenta ajena. Usa el cliente
         *     con privilegio elevado (Auth Admin API) para marcar `auth.users.deleted_at`, que el
         *     trigger `sincronizar_perfil_usuario` ya espeja a `perfiles_usuario.eliminado_at` --
         *     ver `dominio.puertos.GestorCuentaPuerto.eliminar_cuenta`.
         *
         *     Exige reautenticación reciente (JWT emitido hace menos de 10 minutos) -- ver
         *     `dominio.excepciones.ReautenticacionRequerida`.
         */
        post: operations["eliminar_cuenta_identidad_eliminar_cuenta_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Sesiones
         * @description Sesiones (activas y cerradas) del usuario autenticado -- dispositivo, IP, nivel de
         *     autenticación, timestamps de `public.sesiones`. `DatosTokenDep`, no
         *     `ContextoIdentidadDep`: mismo criterio que `obtener_perfil` (tenant-agnóstico).
         */
        get: operations["listar_sesiones_identidad_sesiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/sesiones/{sesion_id}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar Sesion
         * @description Cierra UNA sesión puntual (no todas -- para eso, `POST
         *     /identidad/cerrar-todas-las-sesiones`).
         *
         *     LIMITACIÓN EXPLÍCITA: esto solo marca `sesiones.cerrada_at` (metadata de aplicación).
         *     Supabase Auth no expone una forma de revocar el JWT/refresh token real de una sesión
         *     puntual identificada por este `sesion_id` -- solo revocación GLOBAL (todas las
         *     sesiones del usuario) o de la sesión ACTUAL de quien hace la llamada, y ninguna de
         *     las dos requiere (ni permite) apuntar a un `sesion_id` arbitrario de nuestra tabla
         *     sin poseer el JWT de ESE dispositivo, que este backend no almacena. Ver el docstring
         *     completo en `dominio.puertos.RepositorioSesionesPuerto.cerrar_sesion`.
         */
        post: operations["cerrar_sesion_identidad_sesiones__sesion_id__cerrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Auditoria
         * @description Historial de accesos/cambios sensibles (`auditoria_autenticacion`) del usuario
         *     autenticado -- login/logout/login_fallido/cambios de contraseña/correo/MFA,
         *     paginado (`limite` máx. 100, `pagina` desde 1 vía query params).
         */
        get: operations["listar_auditoria_identidad_auditoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/cambiar-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Contrasena
         * @description El usuario autenticado cambia su propia contraseña -- distinto de
         *     `POST /identidad/restablecer-contrasena` (flujo SIN sesión, vía enlace de correo).
         *
         *     Exige reautenticación reciente (JWT < 10 minutos) Y la contraseña ACTUAL correcta
         *     (reautenticada contra GoTrue, no asumida por tener un JWT válido) -- ver
         *     `aplicacion.cambiar_contrasena`.
         */
        post: operations["cambiar_contrasena_identidad_cambiar_contrasena_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/cambiar-correo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Correo
         * @description Inicia el cambio de correo del usuario autenticado vía el flujo nativo de GoTrue
         *     (`updateUser`). Con `double_confirm_changes = true` (`supabase/config.toml`), GoTrue
         *     envía confirmación a ambas direcciones (actual y nueva) -- el cambio queda pendiente
         *     hasta que se confirme, `202` refleja eso (no `200`, no se completó todavía).
         *
         *     Exige reautenticación reciente (JWT < 10 minutos). Ver
         *     `dominio.excepciones.CorreoNoDisponible` para la nota de anti-enumeración de este
         *     endpoint en particular (distinta -- y más limitada -- que la de registro/login).
         */
        post: operations["cambiar_correo_identidad_cambiar_correo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/mfa/inscribir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscribir Mfa
         * @description Inicia la inscripción de un factor MFA TOTP -- proxy del soporte nativo de
         *     Supabase Auth (`auth.mfa.enroll`), ver `dominio.puertos.AutenticadorMfaPuerto` para
         *     por qué no se reimplementa TOTP a mano. El factor queda `unverified` hasta
         *     `POST /identidad/mfa/verificar-inscripcion`.
         */
        post: operations["inscribir_mfa_identidad_mfa_inscribir_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/mfa/verificar-inscripcion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verificar Inscripcion Mfa
         * @description Confirma el código TOTP generado por la app authenticator del usuario -- activa
         *     el factor y eleva la sesión actual a `aal2` (a cargo de GoTrue,
         *     `auth.mfa.challenge_and_verify`).
         */
        post: operations["verificar_inscripcion_mfa_identidad_mfa_verificar_inscripcion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/mfa/desactivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desactivar Mfa
         * @description Elimina un factor MFA (`auth.mfa.unenroll`). Exige reautenticación reciente (JWT
         *     < 10 minutos) -- extensión de este PR más allá del pedido explícito, ver
         *     `aplicacion.desactivar_mfa` para el razonamiento.
         */
        post: operations["desactivar_mfa_identidad_mfa_desactivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identidad/mfa/factores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Factores Mfa
         * @description Factores MFA (verificados y no verificados) del usuario autenticado -- para que el
         *     frontend sepa si ya tiene 2FA activo y qué `factor_id` usar en
         *     `POST /identidad/mfa/desactivar`.
         */
        get: operations["listar_factores_mfa_identidad_mfa_factores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud
         * @description Liveness check simple, sin dependencias externas -- no confirma acceso a Supabase.
         */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActualizarPerfilPeticion
         * @description Body de `PATCH /identidad/perfil` -- edición PARCIAL: un campo ausente/`None`
         *     significa "no lo toques", nunca "bórralo" (ver `dominio.objetos_valor.CambiosPerfil`).
         *     Solo valida FORMATO acá (URL válida, string no vacío) -- QUÉ columnas se pueden tocar
         *     lo decide únicamente Postgres (RLS + `restringir_columnas_perfil_usuario`), nunca este
         *     esquema ni el caso de uso.
         */
        ActualizarPerfilPeticion: {
            /** Nombre Completo */
            nombre_completo?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Terminos Aceptados At */
            terminos_aceptados_at?: string | null;
            /** Terminos Version */
            terminos_version?: string | null;
            /** Onboarding Completado At */
            onboarding_completado_at?: string | null;
        };
        /**
         * CambiarContrasenaPeticion
         * @description Body de `POST /identidad/cambiar-contrasena` -- distinto de
         *     `RestablecerContrasenaPeticion` (esa es el flujo SIN sesión vía correo). Exige la
         *     contraseña ACTUAL: nunca basta con estar logueado para poder cambiarla (ver
         *     `aplicacion.cambiar_contrasena`).
         */
        CambiarContrasenaPeticion: {
            /** Contrasena Actual */
            contrasena_actual: string;
            /**
             * Nueva Contrasena
             * @description Mínimo 8 caracteres (mínimo de GoTrue).
             */
            nueva_contrasena: string;
        };
        /**
         * CambiarCorreoPeticion
         * @description Body de `POST /identidad/cambiar-correo`. Requiere reautenticación reciente (JWT
         *     < 10 minutos) -- ver `aplicacion.cambiar_correo`. GoTrue envía confirmación por
         *     correo (`double_confirm_changes = true`): el cambio queda pendiente hasta que se
         *     confirme, esta petición solo lo inicia.
         */
        CambiarCorreoPeticion: {
            /**
             * Nuevo Correo
             * Format: email
             */
            nuevo_correo: string;
        };
        /**
         * ContextoIdentidadRespuesta
         * @description Respuesta de `GET /identidad/contexto` -- mapea `ContextoIdentidad` del dominio.
         */
        ContextoIdentidadRespuesta: {
            /** Usuario Id */
            usuario_id: string;
            /** Correo */
            correo: string | null;
            /** Tenant Id */
            tenant_id: string | null;
            /** Rol */
            rol: string;
            sesion: components["schemas"]["SesionRespuesta"] | null;
        };
        /**
         * CredencialesPeticion
         * @description Body de `POST /identidad/registro` y `POST /identidad/iniciar-sesion`.
         */
        CredencialesPeticion: {
            /**
             * Correo
             * Format: email
             */
            correo: string;
            /**
             * Contrasena
             * @description Mínimo 8 caracteres (mínimo de GoTrue).
             */
            contrasena: string;
        };
        /**
         * DatosSesionAuthRespuesta
         * @description Respuesta de `POST /identidad/registro` y `POST /identidad/iniciar-sesion`.
         */
        DatosSesionAuthRespuesta: {
            /** Token Acceso */
            token_acceso: string;
            /** Token Actualizacion */
            token_actualizacion: string;
            /** Usuario Id */
            usuario_id: string;
            /**
             * Expira At
             * Format: date-time
             */
            expira_at: string;
        };
        /**
         * DesactivarMfaPeticion
         * @description Body de `POST /identidad/mfa/desactivar`. Exige reautenticación reciente (JWT <
         *     10 minutos) -- ver `aplicacion.desactivar_mfa`.
         */
        DesactivarMfaPeticion: {
            /** Factor Id */
            factor_id: string;
        };
        /**
         * EventoAuditoriaRespuesta
         * @description Una fila de `GET /identidad/auditoria`.
         */
        EventoAuditoriaRespuesta: {
            /** Id */
            id: string;
            /** Evento */
            evento: string;
            /** Tenant Id */
            tenant_id: string | null;
            /** Ip */
            ip: string | null;
            /** User Agent */
            user_agent: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Creado At
             * Format: date-time
             */
            creado_at: string;
        };
        /**
         * FactorMfaRespuesta
         * @description Una fila de `GET /identidad/mfa/factores`.
         */
        FactorMfaRespuesta: {
            /** Id */
            id: string;
            /** Tipo */
            tipo: string;
            /** Estado */
            estado: string;
            /** Nombre Amistoso */
            nombre_amistoso: string | null;
            /**
             * Creado At
             * Format: date-time
             */
            creado_at: string;
            /**
             * Actualizado At
             * Format: date-time
             */
            actualizado_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InscribirMfaPeticion
         * @description Body de `POST /identidad/mfa/inscribir`.
         */
        InscribirMfaPeticion: {
            /**
             * Nombre Amistoso
             * @description p.ej. "iPhone de Ana"
             */
            nombre_amistoso?: string | null;
        };
        /**
         * InscripcionMfaRespuesta
         * @description Respuesta de `POST /identidad/mfa/inscribir`: secreto/QR para configurar la app
         *     authenticator. El factor queda `unverified` hasta
         *     `POST /identidad/mfa/verificar-inscripcion`.
         */
        InscripcionMfaRespuesta: {
            /** Factor Id */
            factor_id: string;
            /** Secreto */
            secreto: string;
            /** Codigo Qr */
            codigo_qr: string;
            /** Uri */
            uri: string;
            /** Nombre Amistoso */
            nombre_amistoso: string | null;
        };
        /**
         * MensajeRespuesta
         * @description Respuesta genérica de un endpoint sin datos propios que devolver más allá de un
         *     mensaje de confirmación (recuperación de contraseña, restablecimiento).
         */
        MensajeRespuesta: {
            /** Mensaje */
            mensaje: string;
        };
        /**
         * PerfilCuentaRespuesta
         * @description Respuesta de `GET`/`PATCH /identidad/perfil`.
         *
         *     Deliberadamente NO incluye `tenant_id`/`rol` (a diferencia de
         *     `ContextoIdentidadRespuesta`): `perfiles_usuario` no tiene `tenant_id` -- es una fila
         *     por usuario, no por (usuario, tenant) -- y gestión de cuenta debe funcionar para
         *     CUALQUIER usuario autenticado, incluso uno recién registrado sin ninguna fila en
         *     `roles_usuario` todavía (`cliente` se autoasigna recién en su primera reserva) o con
         *     roles en varios tenants sin `X-Tenant-Id` explícito. Exigir un rol/tenant ya resuelto
         *     acá (vía `ContextoIdentidadDep`) bloquearía a esos usuarios con un 403 que no tiene
         *     nada que ver con poder ver/editar su propio perfil -- por eso este endpoint usa
         *     `DatosTokenDep` (solo JWT validado), no `ContextoIdentidadDep`. Reusa igual la MISMA
         *     validación de JWT que `ContextoIdentidadRespuesta` (`ValidadorTokenPuerto`
         *     compartido), solo que sin la resolución de rol/tenant que no aplica acá.
         */
        PerfilCuentaRespuesta: {
            /** Usuario Id */
            usuario_id: string;
            /** Correo */
            correo: string | null;
            /** Nombre Completo */
            nombre_completo: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Terminos Aceptados At */
            terminos_aceptados_at: string | null;
            /** Terminos Version */
            terminos_version: string | null;
            /** Onboarding Completado At */
            onboarding_completado_at: string | null;
        };
        /**
         * RecuperarContrasenaPeticion
         * @description Body de `POST /identidad/recuperar-contrasena`.
         */
        RecuperarContrasenaPeticion: {
            /**
             * Correo
             * Format: email
             */
            correo: string;
        };
        /**
         * RestablecerContrasenaPeticion
         * @description Body de `POST /identidad/restablecer-contrasena`.
         *
         *     `token_acceso`/`token_actualizacion` son el par access/refresh token de la sesión de
         *     RECUPERACIÓN que el frontend obtuvo al abrir el enlace del correo (no la sesión normal
         *     de login) -- Supabase ya validó que ese enlace es legítimo antes de emitirlos.
         */
        RestablecerContrasenaPeticion: {
            /** Token Acceso */
            token_acceso: string;
            /** Token Actualizacion */
            token_actualizacion: string;
            /**
             * Nueva Contrasena
             * @description Mínimo 8 caracteres (mínimo de GoTrue).
             */
            nueva_contrasena: string;
        };
        /**
         * SesionRespuesta
         * @description Respuesta de `GET /identidad/sesiones` (una fila) y de `sesion` en
         *     `ContextoIdentidadRespuesta` -- dispositivo/IP/nivel de autenticación/timestamps de
         *     `public.sesiones`, nunca el JWT en sí.
         */
        SesionRespuesta: {
            /** Id */
            id: string;
            /** Dispositivo */
            dispositivo: string | null;
            /** Ip */
            ip: string | null;
            /** Nivel Autenticacion */
            nivel_autenticacion: string;
            /**
             * Iniciada At
             * Format: date-time
             */
            iniciada_at: string;
            /**
             * Ultima Actividad At
             * Format: date-time
             */
            ultima_actividad_at: string;
            /**
             * Expira At
             * Format: date-time
             */
            expira_at: string;
            /** Cerrada At */
            cerrada_at: string | null;
            /** Activa */
            activa: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificarInscripcionMfaPeticion
         * @description Body de `POST /identidad/mfa/verificar-inscripcion`.
         */
        VerificarInscripcionMfaPeticion: {
            /** Factor Id */
            factor_id: string;
            /**
             * Codigo
             * @description Código TOTP de la app authenticator.
             */
            codigo: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaActualizarPerfilPeticion = components['schemas']['ActualizarPerfilPeticion'];
export type SchemaCambiarContrasenaPeticion = components['schemas']['CambiarContrasenaPeticion'];
export type SchemaCambiarCorreoPeticion = components['schemas']['CambiarCorreoPeticion'];
export type SchemaContextoIdentidadRespuesta = components['schemas']['ContextoIdentidadRespuesta'];
export type SchemaCredencialesPeticion = components['schemas']['CredencialesPeticion'];
export type SchemaDatosSesionAuthRespuesta = components['schemas']['DatosSesionAuthRespuesta'];
export type SchemaDesactivarMfaPeticion = components['schemas']['DesactivarMfaPeticion'];
export type SchemaEventoAuditoriaRespuesta = components['schemas']['EventoAuditoriaRespuesta'];
export type SchemaFactorMfaRespuesta = components['schemas']['FactorMfaRespuesta'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaInscribirMfaPeticion = components['schemas']['InscribirMfaPeticion'];
export type SchemaInscripcionMfaRespuesta = components['schemas']['InscripcionMfaRespuesta'];
export type SchemaMensajeRespuesta = components['schemas']['MensajeRespuesta'];
export type SchemaPerfilCuentaRespuesta = components['schemas']['PerfilCuentaRespuesta'];
export type SchemaRecuperarContrasenaPeticion = components['schemas']['RecuperarContrasenaPeticion'];
export type SchemaRestablecerContrasenaPeticion = components['schemas']['RestablecerContrasenaPeticion'];
export type SchemaSesionRespuesta = components['schemas']['SesionRespuesta'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaVerificarInscripcionMfaPeticion = components['schemas']['VerificarInscripcionMfaPeticion'];
export type $defs = Record<string, never>;
export interface operations {
    obtener_contexto_identidad_contexto_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-tenant-id"?: string | null;
                "x-sesion-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextoIdentidadRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_identidad_registro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatosSesionAuthRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iniciar_sesion_identidad_iniciar_sesion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatosSesionAuthRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_perfil_identidad_perfil_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilCuentaRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_perfil_identidad_perfil_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarPerfilPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilCuentaRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recuperar_contrasena_identidad_recuperar_contrasena_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecuperarContrasenaPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restablecer_contrasena_identidad_restablecer_contrasena_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestablecerContrasenaPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_todas_las_sesiones_identidad_cerrar_todas_las_sesiones_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_cuenta_identidad_eliminar_cuenta_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_sesiones_identidad_sesiones_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionRespuesta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_sesion_identidad_sesiones__sesion_id__cerrar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                sesion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_auditoria_identidad_auditoria_get: {
        parameters: {
            query?: {
                limite?: number;
                pagina?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoAuditoriaRespuesta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_contrasena_identidad_cambiar_contrasena_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarContrasenaPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_correo_identidad_cambiar_correo_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarCorreoPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensajeRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inscribir_mfa_identidad_mfa_inscribir_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InscribirMfaPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InscripcionMfaRespuesta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verificar_inscripcion_mfa_identidad_mfa_verificar_inscripcion_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarInscripcionMfaPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_mfa_identidad_mfa_desactivar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesactivarMfaPeticion"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_factores_mfa_identidad_mfa_factores_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorMfaRespuesta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
